Fix CVE-2021-44228
provectus/kafka-ui pull request #1231
Opened 2021-12-11 23:39 UTC by Haarolean

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing applications:)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "X" next to an item)

- [x] No need to
- [ ] Manually(please, describe, when necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings(e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

2021-12-12 11:38 UTC, asatsi requested changes
Getting error:
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.NoSuchFieldError: EMPTY_BYTE_ARRAY
        at org.apache.logging.log4j.core.config.ConfigurationSource.<clinit>(ConfigurationSource.java:56)
        at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
        at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.commons.logging.LogAdapter$Log4jLog.<clinit>(LogAdapter.java:155)
        at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:122)
        at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:89)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
        at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:201)
        at com.provectus.kafka.ui.KafkaUiApplication.main(KafkaUiApplication.java:14)
        ... 8 more

2021-12-12 22:30 UTC, Haarolean commented
@asatsi I'm well aware, thanks. This is the reason it's still not merged.

2021-12-13 02:33 UTC, asatsi commented
Thanks @Haarolean , would you be able to also bump up llog4j-1.2.17.jar references to log4j2? Cause there's another CVE which blocks us using kafka-ui that uses this jar.

2021-12-13 08:06 UTC, Haarolean commented
@asatsi could you share more details please? Which CVE is that? I was planning on mitigating the issue via setting an environment variable since upgrading log4j is kind of an issue atm.

2021-12-13 11:10 UTC, asatsi commented
@Haarolean this one here: https://nvd.nist.gov/vuln/detail/CVE-2019-17571. It states "log4j_log4j version 1.2.17 has 2 vulnerabilities" in twistlock/prismascan.

2021-12-13 11:31 UTC, Haarolean commented
@asatsi got it, please create a separate issue, since this one is a totally different one.

2021-12-13 11:34 UTC, Haarolean commented
Closing for now, since:
1) The app is not affected since jdk/jre used for our docker image sets has `log4j2.formatMsgNoLookups` with value `true`.
2) Upgrading log4j is currently a problem, will wait for a new spring boot version

2021-12-21 11:37 UTC, iliax requested changes
need to move configs from log4j2.xml to logback.xml

2021-12-22 12:47 UTC, iliax approved these changes

2021-12-22 12:53 UTC, merged