Added readonly status for the cluster.
provectus/kafka-ui pull request #1364
Opened 2022-01-10 13:47 UTC by NelyDavtyan

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing applications:)

**What changes did you make?** (Give an overview)
Issues #1185 
<img width="1752" alt="Screen Shot 2022-01-17 at 4 08 26 PM" src="https://user-images.githubusercontent.com/96067981/149767128-3dc0e3b7-02d4-41e9-9585-35ab78e97716.png">

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "X" next to an item)

- [x] No need to
- [x] Manually(please, describe, when necessary)
- [x] Unit checks
- [x] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings(e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

2022-01-10 18:43 UTC, workshur commented
@NelyDavtyan Could you add screenshot of your change to description of current PR?

2022-01-11 10:15 UTC, Hurenka requested changes

2022-01-11 10:15 UTC, Hurenka commented on kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.tsx
> +                    <div className="tag has-margin-right is-info is-light">
We're trying to use own styles with the styled-components and without classnames, aren't we?

2022-01-12 18:03 UTC, workshur commented on kafka-ui-react-app/src/theme/theme.ts
> +    '40': '#64b5f6',
Are these colors from figma?

2022-01-14 08:43 UTC, workshur approved these changes

2022-01-17 11:54 UTC, Hurenka approved these changes

2022-01-17 12:57 UTC, Hurenka commented on kafka-ui-react-app/src/components/common/Tag/Tag.styled.tsx
> +  className?: string;
remove unused className prop, please

2022-01-17 13:39 UTC, workshur approved these changes

2022-01-17 14:15 UTC, Motherships approved these changes

2022-01-17 14:29 UTC, merged