Restrict domains with google SSO
provectus/kafka-ui pull request #1446
Opened 2022-01-21 10:48 UTC by Haarolean

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing applications:)

**What changes did you make?** (Give an overview)
Restrict auth domains with google SSO
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "X" next to an item)

- [ ] No need to
- [x] Manually(please, describe, when necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings(e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

2022-01-21 12:38 UTC, iliax approved these changes

2022-01-26 08:18 UTC, germanosin requested changes
I see that this one is specific only for google, props, and code. Could we think about a more general solution? As for workaround for now users could pass hd var in config token url.

2022-08-02 13:13 UTC, Haarolean commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/auth/OAuthSecurityConfig.java
> +        if (domainAttribute == null) {
I like step-by-step approach with extensive logging here

2022-08-03 15:17 UTC, daching-provectus approved these changes

2022-10-14 08:29 UTC, closed without merging