[754] Define listing of Acls API
provectus/kafka-ui pull request #1511
Opened 2022-01-28 19:17 UTC by jonasgeiregat

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing applications:)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "X" next to an item)

- [ ] No need to
- [ ] Manually(please, describe, when necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ ] My changes generate no new warnings(e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

2022-02-08 17:35 UTC, Haarolean requested changes
@jonasgeiregat can we return whole `AclBinding` instead of `AccessControlEntry`?

2022-02-08 20:28 UTC, jonasgeiregat commented
> @jonasgeiregat can we return whole `AclBinding` instead of `AccessControlEntry`?

You mean instead of `/api/clusters/{clusterName}/acls/{resourceType}` just the list of all Acls per cluster like `/api/clusters/{clusterName}/acls` ?

2022-02-10 12:43 UTC, Haarolean commented
> > @jonasgeiregat can we return whole `AclBinding` instead of `AccessControlEntry`?
> 
> You mean instead of `/api/clusters/{clusterName}/acls/{resourceType}` just the list of all Acls per cluster like `/api/clusters/{clusterName}/acls` ?

You're returning a list of `AccessControlEntry`, but I'd like to see `AclBinding`, which is a parent entity.

2022-02-10 12:43 UTC, Haarolean requested changes

2022-02-10 12:43 UTC, Haarolean commented on kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
> +        - totalReplicationFactor
What's that?

2022-04-21 02:11 UTC, closed without merging