Mock server removal
provectus/kafka-ui pull request #157
Opened 2021-01-18 09:31 UTC by Guzel738

- mock server directory removed

2021-01-18 12:22 UTC, aMoRRoMa commented
HI! It would be great to update README.md too.

2021-01-19 09:54 UTC, Guzel738 commented
- package.json and README updated

2021-01-19 09:55 UTC, aMoRRoMa commented on kafka-ui-react-app/README.md
> -Start JSON Server if you prefer to use default full fake REST API.
If mock API is deleted, lines from 23 to 26 don't make sense.

2021-01-19 10:03 UTC, workshur requested changes
Please check and remove all dependencies related to this mock server, e.g: `json-server`

2021-01-19 12:05 UTC, Guzel738 commented
Dependencies related to mock server removed, README file updated

2021-01-19 12:11 UTC, workshur approved these changes

2021-01-19 12:59 UTC, soffest approved these changes

2021-01-19 13:17 UTC, whotake approved these changes
Looks good 👍

2021-01-19 13:41 UTC, aMoRRoMa approved these changes

2021-01-20 12:05 UTC, merged