[FIXED issue/1545] added feedback to the user when a message content is copied to clipboard
provectus/kafka-ui pull request #1570
Opened 2022-02-07 17:11 UTC by Dekshut

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Added success Alert after the message was copied to clipboard
**Is there anything you'd like reviewers to focus on?**
Auto-dissmis time and stylistic

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [X] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [X] My changes generate no new warnings (e.g. Sonar is happy)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-02-08 07:34 UTC, NelyDavtyan commented on kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/Message.tsx
> +  const test = () => {
it's not a good idea to name a variable 'test',change the name please

2022-02-08 14:25 UTC, Motherships approved these changes

2022-02-08 14:25 UTC, Motherships commented on kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
> +const AUTO_DISSMISS_TIME = 2000;
Typo
```suggestion
const AUTO_DISMISS_TIME = 2000;
```

2022-02-08 14:25 UTC, Motherships commented on kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
> +      setTimeout(() => dispatch(alertDissmissed(subject)), AUTO_DISSMISS_TIME);
Cool 
I will use same thing in my PR

2022-02-08 14:27 UTC, NelyDavtyan approved these changes

2022-02-08 15:06 UTC, abelgibayev requested changes

2022-02-08 15:06 UTC, abelgibayev commented on kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
>    const copyToClipboard = () => {
Move dispatch outside copyToClipboard, the hooks should be called only in other hook/component 1st level scope

2022-02-10 06:57 UTC, abelgibayev approved these changes

2022-02-10 06:58 UTC, merged