[ISSUE-1013]Clone topic functionality
provectus/kafka-ui pull request #1631
Opened 2022-02-17 22:27 UTC by ValentinPrischepa

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Added a new endpoint for cloning topics from the existing one. Also, there is an optional parameter for cloning with all topic messages.
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [X] Manually (please, describe, if necessary)
- [ ] Unit checks
- [X] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [X] My changes generate no new warnings (e.g. Sonar is happy)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-02-18 06:50 UTC, iliax requested changes

2022-02-18 09:08 UTC, Haarolean commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/MessagesService.java
> +                                         ConsumerPosition consumerPosition) {
Let's clone just the topic with its configuration without messages.

2022-02-21 06:46 UTC, iliax approved these changes

2022-02-21 10:37 UTC, Haarolean approved these changes
@ValentinPrischepa good to merge once [the labels](https://github.com/provectus/kafka-ui/pull/1479) are set and the build passes.

2022-03-14 09:39 UTC, merged