Add CRUD actions for Schema Registry service
provectus/kafka-ui pull request #165
Opened 2021-01-29 08:28 UTC by IldarAlmakaev

The following endpoints have been implemented:
<img width="843" alt="Screenshot 2021-01-29 at 10 42 52" src="https://user-images.githubusercontent.com/11831199/106250676-0741d900-6225-11eb-9165-af5c67540748.png">

2021-01-31 16:30 UTC, workshur approved these changes

2021-02-03 10:28 UTC, germanosin requested changes

2021-02-03 10:28 UTC, germanosin commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/service/SchemaRegistryService.java
> +    private Flux<SchemaSubject> getSchemaSubject(String clusterName, String subjectName, String version) {
Maybe it should be Mono?

2021-02-03 10:28 UTC, germanosin commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/cluster/service/SchemaRegistryService.java
> +                        .onStatus(HttpStatus.NOT_FOUND::equals, resp -> Mono.error(new NotFoundException("No such subject or version")))
1. What about 5xx statuses
2. Don't you mind make status handling generic?

2021-02-03 10:28 UTC, germanosin commented on kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
> +                  $ref: '#/components/schemas/SchemaSubject'
Why is it array?

2021-02-03 10:28 UTC, germanosin commented on kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
> +                type: array
Why is it array?

2021-02-03 10:28 UTC, germanosin commented on kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
> +  /api/clusters/{clusterName}/schemas/compatibility/{schemaName}:
let's return compatibility inside schemaobject

2021-02-03 10:28 UTC, germanosin commented on kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
> +    put:
/api/clusters/{clusterName}/schemas/compatibility/{schemaName} ->
PUT /api/clusters/{clusterName}/schemas/{schemaName}/compatibility

2021-02-03 10:28 UTC, germanosin commented on kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
> +  /api/clusters/{clusterName}/schemas/compatibility/{schemaName}/check:
/api/clusters/{clusterName}/schemas/{schemaName}/check

2021-02-03 10:28 UTC, germanosin commented on kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
> +        schema:
Let's add compatibility here

2021-02-09 07:39 UTC, germanosin approved these changes

2021-02-09 07:40 UTC, merged