Add protobufMessageNameForKeyByTopic option to config. Message keys are
provectus/kafka-ui pull request #1729
Opened 2022-03-14 15:57 UTC by jdechicchis

Closes #1699 

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Add protobufMessageNameForKeyByTopic option to config. Message keys are deserialized using a protobuf schema if the config is set. Otherwise message keys are treated as strings.

**Is there anything you'd like reviewers to focus on?**
Name of configuration and unit tests as well as style.

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x ] Manually (please, describe, if necessary)
- [x ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ ] My changes generate no new warnings (e.g. Sonar is happy)
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [x ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-03-15 07:41 UTC, Haarolean commented
@jdechicchis thanks for the contribution!

2022-03-20 10:25 UTC, iliax requested changes

2022-03-20 10:25 UTC, iliax commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java
> +        }
Lets implement logic like it is currently implemented in [SchemaAwareSD](https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/schemaregistry/SchemaRegistryAwareRecordSerDe.java#L115). 

1.  if descriptor not found -> use FALLBACK_FORMATTER (StringMessageFormatter)
2. if descriptor found, but there was an error in deserialization -> trace error and use  FALLBACK_FORMATTER.

2022-03-20 10:32 UTC, iliax commented
Hi @jdechicchis!  
Thank you for your PR, please see comments.

In addition to them -> we should also edit `serialize` method to support sending messages with proto keys via kafka-ui.
Logic should be:
1. if there is **no** descriptor for topic's k or v -> treat (k or v) as a string - `kOrV.getBytes();`
2. if there is a descriptor for k/v -> use descriptor for serialization. If there is an serialization error - you should throw  `ValidationException` exception

2022-03-22 14:18 UTC, jdechicchis commented
@iliax Thank you for the review. I was wondering what to do about `defaultMessageDescriptor` based on your feedback. It's currently only used as a fallback to deserialize the message's value, but based on your feedback I think it may make sense to remove `defaultMessageDescriptor` and fallback to `FALLBACK_FORMATTER (StringMessageFormatter)` if the descriptor isn't found (for either key or value)

2022-03-24 20:22 UTC, iliax commented
@jdechicchis Thank you for highlighting it, I actually forgot `defaultMessageDescriptor` logic... We currently can't remove this, because it will break backward-compatibility. 
I think most the most proper way is to add `Cluster.protobufMessageNameForKey` property and use it as default for topic's keys that have no explicit mapping. If `protobufMessageNameForKey` is not specified or there was an error during initializing - we should fallback to StringMessageFormatter

2022-03-29 20:23 UTC, jdechicchis commented
@iliax Thanks for the clarification, updated based on the feedback.

By the way, the "Documentation / build-and-test (pull_request)" check is failing with the error:
```
Done. The following urls did not pass:
https://dev-a63ggcut.auth0.com/
```
even though I didn't add that URL. What's the best way to resolve it?

2022-03-29 23:24 UTC, Haarolean commented
That build fail is not your fault. Just ignore it for now. 

> On 30 Mar 2022, at 00:23, Joseph DeChicchis ***@***.***> wrote:
> 
> ﻿
> @iliax Thanks for the clarification, updated based on the feedback.
> 
> By the way, the "Documentation / build-and-test (pull_request)" check is failing with the error:
> 
> Done. The following urls did not pass:
> https://dev-a63ggcut.auth0.com/
> even though I didn't add that URL. What's the best way to resolve it?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were assigned.

2022-04-04 09:38 UTC, iliax commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java
> +          log.error("Failed to deserialize key as protobuf, falling back to string formatter", e);
lets use debug level here - otherwise logs can appear on every msg

2022-04-04 09:38 UTC, iliax commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java
> +        log.error("Failed to deserialize value as protobuf, falling back to string formatter", e);
debug level here too

2022-04-04 09:38 UTC, iliax commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java
> +
pls add `@Nullable` annotation here to highlight that result can be null

2022-04-04 09:38 UTC, iliax commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java
> +                                 String defaultKeyMessageName)
pls add `@Nullable` to defaultKeyMessageName arg

2022-04-04 09:40 UTC, iliax commented
Hi @jdechicchis !
Thank you for great job - I added just a couple of small comments - pls fix them and we will be ready to merge

2022-04-05 11:52 UTC, iliax approved these changes

2022-04-05 12:11 UTC, Haarolean approved these changes

2022-04-05 12:26 UTC, merged