Issues/1525 add sort order consumer group page
provectus/kafka-ui pull request #1747
Opened 2022-03-23 07:45 UTC by Mgrdich

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
* Implement Sorting to the Consumer Groups Page
* Transform the Consumer Group Page to the SmartTable Structure
* Styling fix for the Order indication

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-03-23 10:42 UTC, Mgrdich commented
The Tests coverage include all the new Features that was added , but i think we need a separate issue to write test for the new tables.

2022-03-23 13:25 UTC, workshur approved these changes

2022-03-24 08:38 UTC, sasunprov requested changes

2022-03-24 08:38 UTC, sasunprov commented on kafka-ui-react-app/src/components/ConsumerGroups/List/ConsumerGroupsTableCells.tsx
> +  return <span>{coordinator?.id}</span>;
you can pass "coordinator.id" to TableColumn component. it will lookup property's value

2022-03-24 08:38 UTC, sasunprov commented on kafka-ui-react-app/src/components/ConsumerGroups/List/List.tsx
> +        <TableColumn title="Coordinator" cell={CoordinatorCell} />
please pass field prop with value "coordinator.id" and remove custom component for this column

2022-03-24 08:38 UTC, sasunprov commented on kafka-ui-react-app/src/components/common/SmartTable/SmartTable.tsx
> +    if (allSelectable) {
if(selectable) {
   checkboxElement = allSelectable ? <SelectCell
          rowIndex={-1}
          el="th"
          selectable
          selected={tableState.selectedCount === tableState.data.length}
          onChange={tableState.toggleSelection}
        /> : <S.TableHeaderCell />
}

2022-03-24 09:04 UTC, sasunprov approved these changes

2022-03-24 09:44 UTC, merged