Issues/1741 smart filters
provectus/kafka-ui pull request #1814
Opened 2022-04-09 19:47 UTC by Mgrdich

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Implementing new UX UI for smart Filters + adding react testing hook library for custom hooks tests suites

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-04-11 07:18 UTC, lazzy-panda approved these changes

2022-04-11 08:15 UTC, workshur approved these changes

2022-04-11 11:50 UTC, Haarolean commented
Let’s make it possible to apply a filter without setting a name for it (in case the checkbox is unchecked).

2022-04-11 11:51 UTC, Haarolean requested changes
Let’s make it possible to apply a filter without setting a name for it (in case the checkbox is unchecked).

2022-04-13 14:50 UTC, iliax commented
I checked Custom deployment - currently smth strange is passing as `q` parameter - filter code should be there instead. 
cc @Haarolean

2022-04-18 10:08 UTC, Haarolean approved these changes

2022-04-18 10:14 UTC, merged