Added Social icons
provectus/kafka-ui pull request #2137
Opened 2022-06-07 12:02 UTC by lazzy-panda

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

2022-06-07 15:34 UTC, workshur requested changes
We are using styled-components approach

2022-06-07 15:34 UTC, workshur commented on kafka-ui-react-app/src/components/common/Icons/DiscordIcon.tsx
> +const GitIcon: React.FC = () => {
Git or discord?

2022-06-07 15:42 UTC, lazzy-panda commented on kafka-ui-react-app/src/components/App.tsx
> +              $clickColor="#171A1C"
Opening a link..

2022-06-08 09:11 UTC, Mgrdich commented on kafka-ui-react-app/src/components/App.tsx
> +              $clickColor="#171A1C"
`<Link to="route" target="_blank"` Something like this will help you to redirect

2022-06-08 09:11 UTC, Mgrdich commented on kafka-ui-react-app/src/components/App.tsx
> +              $clickColor="#171A1C"
instead of a div in the styled components

2022-06-08 09:39 UTC, lazzy-panda commented on kafka-ui-react-app/src/components/App.tsx
> +              $clickColor="#171A1C"
@Mgrdich , this approach doesn't work with external links.

2022-06-08 09:53 UTC, lazzy-panda commented on kafka-ui-react-app/src/components/common/Icons/DiscordIcon.tsx
> +const GitIcon: React.FC = () => {
fixed

2022-06-08 11:49 UTC, workshur commented on kafka-ui-react-app/src/components/App.tsx
> +              $clickColor="#171A1C"
Just try `to={{ pathname: "https://example.com" }}`

2022-06-08 12:26 UTC, lazzy-panda commented on kafka-ui-react-app/src/components/App.tsx
> +              $clickColor="#171A1C"
@workshur, 
this code add new path to the old
`<Link to={{ pathname: 'https://github.com/provectus/kafka-ui' }}>
                <GitIcon />
              </Link>`
<img width="730" alt="image" src="https://user-images.githubusercontent.com/22497195/172615461-598ae5af-216b-4323-a336-29e424d16434.png">

2022-06-09 09:09 UTC, Haarolean requested changes
- discord active icon's color is a wrong one
<img width="295" alt="image" src="https://user-images.githubusercontent.com/1494347/172714649-3650fe49-2714-4fbe-9a17-49fda72769b4.png">

- github icon color doesn't change upon click

- discord's icon is a bit higher than github's
<img width="217" alt="image" src="https://user-images.githubusercontent.com/1494347/172810362-437fbe03-23e2-4408-8940-207b33c1d847.png">

2022-06-09 11:33 UTC, lazzy-panda commented
> * discord active icon's color is a wrong one
> 
> <img alt="image" width="295" src="https://user-images.githubusercontent.com/1494347/172714649-3650fe49-2714-4fbe-9a17-49fda72769b4.png">
> 
> * github icon color doesn't change upon click
> * discord's icon is a bit higher than github's
> 
> <img alt="image" width="217" src="https://user-images.githubusercontent.com/1494347/172810362-437fbe03-23e2-4408-8940-207b33c1d847.png">

@Haarolean, I fixed the size and position oh the icons. The colour of the GitIcon is changing but you can't detect it because of not big difference between colours. I can increase the contrast but it will differ from the color in design.

2022-06-10 15:40 UTC, Haarolean requested changes
active discord icon color is still a wrong one

2022-06-16 16:37 UTC, Haarolean approved these changes

2022-06-21 12:23 UTC, workshur approved these changes

2022-06-21 12:23 UTC, merged