Support prometheus as a metrics interface
provectus/kafka-ui pull request #2190
Opened 2022-06-21 07:36 UTC by MaratGumarov

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

2022-07-15 14:24 UTC, Haarolean commented
@germanosin PTAL

2022-08-04 09:50 UTC, germanosin requested changes

2022-08-04 09:50 UTC, germanosin commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/model/KafkaCluster.java
>    private final Integer jmxPort;
I would suggest to rename:
1. Metrics
1.1 port
1.2 type: JMX/PrometheusEndpoint
1.3 basicAuth
1.3.1 username
1.3.2 password
1.4 ssl 
1.4.1 enabled true
1.4.2 truststore
1.4.3 keystore

2022-08-04 09:52 UTC, germanosin commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/util/JmxExporterMetricsParser.java
> +public class JmxExporterMetricsParser {
PrometheusEndpointMetricsParser?

2022-08-19 15:03 UTC, Haarolean approved these changes

2022-10-05 11:57 UTC, Haarolean approved these changes

2022-10-05 11:57 UTC, Haarolean commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/WellKnownMetrics.java
> +  void feed(KafkaCluster cluster, Node node, RawMetric rawMetric) {
feed -> populate ?

2022-10-05 12:06 UTC, iliax commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/WellKnownMetrics.java
> +  void feed(KafkaCluster cluster, Node node, RawMetric rawMetric) {
done

2022-10-07 10:36 UTC, merged