WIP: #190 JSON export
provectus/kafka-ui pull request #236
Opened 2021-03-10 13:30 UTC by GneyHabub

Now there are 2 buttons over each _Content_ field of the Messages table. 

![image](https://user-images.githubusercontent.com/31561808/110671786-f9965080-81df-11eb-9503-71f3fadea911.png)

If you hover over any of them there will be a popup hint which tells the user what this button does:

![image](https://user-images.githubusercontent.com/31561808/110671636-d1a6ed00-81df-11eb-95f2-0bc56718f75d.png)
![image](https://user-images.githubusercontent.com/31561808/110672069-41b57300-81e0-11eb-84d1-67408d206df0.png)

The first button will copy the Content to the clipboard and the second will trigger a file download (`.json` if the content is an object or `JSON.parse` doesn't throw an exception; `.txt` otherwise.)

2021-03-10 14:21 UTC, workshur commented
1. Please add description 
2. Add screenshot

2021-03-10 18:24 UTC, workshur requested changes
1. We need to move buttons to JSONViewer component.
2. Use standard bulma buttons

2021-03-10 18:24 UTC, workshur commented on kafka-ui-react-app/src/components/App.scss
> +}
It is important to reduce custom stuff. Let's use native title

2021-03-15 12:06 UTC, GneyHabub commented
I have no idea how to test the file download yet. Still working on it.

2021-03-16 10:47 UTC, GneyHabub commented
Okay, after some research I've got an impression that the file-downloading part of the functionality is pretty much untestable. I didn't find a way to trigger the file download inside of the testing environment. 
It is possible to dig into the specific implementation and test it, but this seems wrong to me. In this way, we treat the component as a white box, exposing all of its guts, tying our tests to the specific implementation. Looks like a violation of a bunch of principles and good practises. 
@workshur @whotake what do you think?

2021-03-17 08:42 UTC, workshur approved these changes

2021-03-17 09:44 UTC, whotake commented
@GneyHabub Does it throw any errors when are you trying to test it?

I think we can split view and download logic and test them separately:

1. Test view that it calls `saveFile` with proper arguments
2. Test `saveFile` itself. And there a few options on how to do it:
2.1 Split function into modules and test important logic. We care about file name and content more than pretty much standard downloading function.
2.2 Mock `document` and check `setAttribute` to content
2.3 Combine two methods above

2021-03-17 09:45 UTC, whotake commented on kafka-ui-react-app/src/components/Topics/Details/Messages/MessageItem.tsx
> +          <JSONViewer data={content as { [key: string]: string }} />
tip: `Record<string, string>`

2021-03-17 09:45 UTC, whotake commented on kafka-ui-react-app/src/components/common/JSONViewer/JSONViewer.tsx
> +        style={{
You can use Bulma helpers https://bulma.io/documentation/helpers/flexbox-helpers/#justify-content

2021-03-17 09:45 UTC, whotake commented on kafka-ui-react-app/src/components/common/JSONViewer/JSONViewer.tsx
> +          style={{ marginRight: '5px' }}
Same here

2021-03-22 06:43 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageItem.tsx
> +        </div>
What is this div for?

2021-03-22 11:01 UTC, GneyHabub commented on kafka-ui-react-app/src/components/Topics/Topic/Details/Messages/MessageItem.tsx
> +        </div>
Yep, got rid of it

2021-03-22 15:36 UTC, merged