message
provectus/kafka-ui pull request #2590
Opened 2022-09-15 12:04 UTC by habrahamyanpro

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ ] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-09-15 17:47 UTC, workshur requested changes
Please follow my review comments and fix linting issues

2022-09-15 17:47 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
> +          <div>{formatTimestamp(timestamp, timeStampFormat)}</div>
I see no need of getting timeStampFormat in every place we use `formatTimestamp`. 

Please load `timeStampFormat` once and use inside of `formatTimestamp` helper

2022-09-15 17:47 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
> +import { TimeStampFormat } from 'generated-sources/models/TimeStampFormat';
```suggestion
import { TimeStampFormat } from 'generated-sources';
```

2022-09-16 07:40 UTC, habrahamyanpro commented on kafka-ui-react-app/src/lib/constants.ts
> +export const BASE_URL = 'http://pr2583.internal.kafka-ui.provectus.io';
I'm waiting for BE to be merged and then I'll change it to get from `.env.local`, as warned in the slack I'm using development deployed url for now and will change it to get from env after getting backend merged and working

2022-09-16 12:05 UTC, workshur commented on kafka-ui-react-app/src/components/App.tsx
> +          <TimeFormatContextProvider>
GlobalSettings

2022-09-16 12:05 UTC, workshur commented on kafka-ui-react-app/src/lib/hooks/useTimeFormat.ts
> +  return formatTimestamp(timestamp, timeStampFormat);
(timestamp) =>  
```suggestion
  return (timestamp) =>  formatTimestamp(timestamp, timeStampFormat);
```

2022-09-16 12:07 UTC, workshur commented on kafka-ui-react-app/src/lib/hooks/api/timeFormat.ts
> +  return useQuery(['timestampformat'], () => api.getTimeStampFormat());
add default value

2022-09-16 19:33 UTC, Haarolean requested changes
1. Date format used currently is a weird one:
![image](https://user-images.githubusercontent.com/1494347/190716697-a48da8c2-29fb-4d12-a336-e3d950a27145.png)
2. There are no calls to `/api/info/timestampformat` API endpoint as far as I see.

2022-09-19 08:32 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Statistics/Metrics.tsx
> +          <span>{formatTimestamp(data?.progress?.startedAt)}</span>
I would suggest to use keep prev version here because we need only 'hh:mm:ss a'

2022-09-20 08:02 UTC, workshur commented on kafka-ui-react-app/src/lib/dateTimeHelpers.ts
> +
I don't think we need to transform format from user settings

2022-09-20 18:09 UTC, habrahamyanpro commented
is ready

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/components/Version/Version.tsx
> +  const { data: actuatorInfo } = useActuatorInfoStats();
```suggestion
  const { data: actuatorInfo = {} } = useActuatorInfoStats();
```

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/components/Version/Version.tsx
>    }, [tag]);
Use useQuery with no refetches

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/components/Version/__tests__/Version.spec.tsx
> +    const element = screen.getByTestId('data_commit_wrapper');
do not use test ids!

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/components/contexts/GlobalSettingsContext.tsx
> +type GlobalSettingsType = {
```suggestion
interface GlobalSettingsType {
```

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/lib/hooks/api/timeFormat.ts
> +  return useQuery(['timestampformat'], fetchTimeFormat);
add options to reduce refetches

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/lib/constants.ts
> +export const VERSION_PATTERN = /v\d.\d.\d/;
```suggestion
export const BUILD_VERSION_PATTERN = /v\d.\d.\d/;
```

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/lib/hooks/api/actuatorInfo.ts
> +  return useQuery(['actuatorInfo'], fetchActuatorInfo);
no refetch

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/lib/hooks/api/brokers.ts
> +      } as UpdateBrokerConfigByNameRequest),
It should be fixed. Pls try to remove

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/lib/api.ts
> +export const timerStampFormat = new TimeStampFormatApi(apiClientConf);
```suggestion
export const timerStampFormatApiClient = new TimeStampFormatApi(apiClientConf);
```

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/lib/hooks/api/actuatorInfo.ts
> +  return useQuery(['actuatorInfo'], fetchActuatorInfo);
```suggestion
  return useQuery(['actuatorInfo'], timerStampFormatApiClient.getTimeStampFormat());
```

2022-09-23 11:46 UTC, workshur commented on kafka-ui-react-app/src/lib/hooks/api/timeFormat.ts
> +  return useQuery(['timestampformat'], fetchTimeFormat);
```suggestion
  return useQuery(['settings', 'timestampformat'], timerStampFormatApiClient.getTimeStampFormat());
```

2022-09-27 14:40 UTC, workshur commented on kafka-ui-react-app/src/components/Version/Version.tsx
> +      {tag && (
No need to check tag existing again. You have already checked it on L32

2022-09-27 14:41 UTC, workshur approved these changes

2022-09-27 14:41 UTC, workshur commented on kafka-ui-react-app/src/components/Version/Version.tsx
> +      {tag && (
Please fix this issue and merge

2022-09-28 11:22 UTC, workshur approved these changes

2022-09-28 11:23 UTC, workshur approved these changes

2022-09-28 11:23 UTC, merged