Add "Total size" of Partition within Topic's statistics #2536
provectus/kafka-ui pull request #2662
Opened 2022-09-27 16:57 UTC by David-DB88

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Added total size in Partition within Topic's statistics 

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ ] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-09-28 12:24 UTC, workshur approved these changes

2022-09-28 12:25 UTC, workshur commented
@Haarolean pls take a look 👀

2022-09-29 08:27 UTC, Haarolean requested changes
![image](https://user-images.githubusercontent.com/1494347/192980633-31446106-b908-4d75-a9a9-f3e0232815a6.png)
Please make it human-readable just like the other sizes

2022-09-29 11:06 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Statistics/PartitionInfoRow.tsx
> +          <span>{(keySize?.sum || 0) + (valueSize?.sum || 0)}</span>
pls use BytesFormatted here

2022-09-29 13:52 UTC, David-DB88 commented on kafka-ui-react-app/src/components/Topics/Topic/Statistics/PartitionInfoRow.tsx
> +          <span>{(keySize?.sum || 0) + (valueSize?.sum || 0)}</span>
done

2022-09-30 11:41 UTC, workshur approved these changes
Looks good to me. @Haarolean please take a look again

2022-10-04 12:30 UTC, Haarolean approved these changes

2022-10-04 12:31 UTC, merged