Add warning message for Danger zone in case of editing the Topic #2534
provectus/kafka-ui pull request #2663
Opened 2022-09-27 20:11 UTC by David-DB88

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Added warning message for Danger zone in case of editing the Topic
 
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-09-28 12:26 UTC, workshur requested changes

2022-09-28 12:26 UTC, workshur commented on kafka-ui-react-app/src/theme/theme.ts
> +  },
pls use existing palete

2022-09-29 13:51 UTC, David-DB88 commented on kafka-ui-react-app/src/theme/theme.ts
> +  },
done

2022-09-30 11:42 UTC, workshur approved these changes
@Haarolean pls take a look 👀

2022-09-30 12:54 UTC, Haarolean requested changes

2022-09-30 12:54 UTC, Haarolean commented on kafka-ui-react-app/src/components/Topics/Topic/Edit/DangerZone/DangerZone.tsx
> +        Change these parameters only if you are absolutely sure that you are
```suggestion
        Change these parameters only if you are absolutely sure what you are
```

2022-09-30 12:55 UTC, Haarolean approved these changes

2022-09-30 13:04 UTC, merged