#2325 Make connectors table rows clickable and #2076 Implement connec…
provectus/kafka-ui pull request #2689
Opened 2022-10-01 02:20 UTC by Kris-K-Dev

…tors sorting

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

Fixes #2325 and #2076

**What changes did you make?** (Give an overview)

Make connectors table rows clickable and Implement connectors sorting

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**
<img width="600" alt="Screenshot 2022-09-30 at 21 19 25" src="https://user-images.githubusercontent.com/92114648/193379264-bbb489bc-ff82-4030-b625-f99588ef2a59.png">

2022-10-01 11:01 UTC, workshur commented
@Haarolean pls take a look 👀

2022-10-02 07:30 UTC, Haarolean requested changes
status sorting doesn't seem to work proeprly
<img width="142" alt="image" src="https://user-images.githubusercontent.com/1494347/193443169-577ea1e2-aac4-41a4-aa40-854a21db2673.png">

2022-10-04 00:19 UTC, Kris-K-Dev commented
> status sorting doesn't seem to work proeprly <img alt="image" width="142" src="https://user-images.githubusercontent.com/1494347/193443169-577ea1e2-aac4-41a4-aa40-854a21db2673.png">

Could you please check it now? Thank you

2022-10-04 12:46 UTC, Haarolean commented
@VladSenyuta it seems like we broke something here

2022-10-04 12:46 UTC, Haarolean approved these changes

2022-10-04 14:16 UTC, VladSenyuta commented
> @VladSenyuta it seems like we broke something here

fixed

2022-10-04 14:17 UTC, VladSenyuta approved these changes

2022-10-05 09:05 UTC, Haarolean commented
@Kris-K-Dev good to merge
@workshur we need an approve here

2022-10-05 09:09 UTC, workshur reviewed
Pls increase test coverage. It should be at least 80%

2022-10-06 09:13 UTC, workshur commented on kafka-ui-react-app/src/components/Connect/List/TopicsCell.tsx
> +          <Link color="#4C4CFF" to={clusterTopicPath(clusterName, t)}>
Pls use styled components attr to change link color. Or update Tag styles to show link correctly

2022-10-07 07:44 UTC, workshur approved these changes

2022-10-07 15:20 UTC, merged