Topic analysis improvements
provectus/kafka-ui pull request #2691
Opened 2022-10-01 06:02 UTC by habrahamyanpro

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ ] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-10-01 10:59 UTC, workshur requested changes
calculate the diff time between the beginning of the process and now

2022-10-01 10:59 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Statistics/Metrics.tsx
> +
> Display time passed since the start

I see that you show time passed since component mount not since analyzing start

2022-10-04 07:50 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Statistics/__test__/__snapshots__/Statistics.spec.tsx.snap
> +exports[`Statistics when analysis is in progress renders Metricks component 1`] = `<div />`;
pls remove it

2022-10-04 07:56 UTC, workshur requested changes
calculate time since `data.progress.startedAt`

2022-10-05 09:11 UTC, workshur commented on kafka-ui-react-app/src/lib/dateTimeHelpers.ts
> +};
pls add tests for `calculateTimer`

2022-10-07 07:40 UTC, workshur approved these changes

2022-10-07 07:40 UTC, workshur commented on kafka-ui-react-app/src/lib/__test__/dateTimeHelpers.spec.ts
> +  });
what are you testing here?

2022-10-07 07:40 UTC, workshur commented on kafka-ui-react-app/src/lib/__test__/dateTimeHelpers.spec.ts
> +  expect(passedTimeMck(10)).toBeTruthy();
should be wrapped to `it`

2022-10-10 07:51 UTC, workshur approved these changes

2022-10-10 07:52 UTC, workshur commented
@Haarolean pls take a look 👀

2022-10-10 16:12 UTC, Haarolean requested changes
1. Rename "passed at' to "passed since start"
2. "scanned bytes" -> "scanned size"

2022-10-25 20:04 UTC, Haarolean commented
<img width="301" alt="image" src="https://user-images.githubusercontent.com/1494347/197870572-e420420c-2076-487c-8a9b-efab9635997d.png">
1. extra spaces around ":" in "passed since start"
2. "passed since start" has a weird format "min:sec s"?? let's remove the "s"
3. overall margin/alignment looks ugly: everything is centered, but the text labels are centered on the right and it looks bad overall

2022-10-25 20:05 UTC, Haarolean requested changes
a few minor issues left

2022-10-28 16:14 UTC, Haarolean approved these changes
@habrahamyanpro please take a look at linter warnings
@armenuikafka please do your thing :)

2022-11-01 20:21 UTC, armenuikafka approved these changes

2022-11-07 11:23 UTC, merged