Migrate Dashboard table to the new version on table components #2682
provectus/kafka-ui pull request #2694
Opened 2022-10-02 00:07 UTC by David-DB88

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Migrate Dashboard table to the new version on table components.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-10-03 11:01 UTC, workshur requested changes
Looks good so far but still need some changes

2022-10-03 11:01 UTC, workshur commented on kafka-ui-react-app/src/components/common/NewTable/LinkTopic.tsx
> +
I don't like the approach when we create toipc link component. Let's try to create universal component where we will send `to` as a property

2022-10-03 11:01 UTC, workshur commented on kafka-ui-react-app/src/components/Dashboard/ClustersWidget/__test__/ClustersWidget.spec.tsx
> -  });
Not sure why we need to remove this test case

2022-10-04 07:22 UTC, workshur requested changes

2022-10-04 07:22 UTC, workshur commented on kafka-ui-react-app/src/components/common/NewTable/LinkTopic.tsx
> +const LinkTopic = ({ row, to }: any) => {
let's call it LinkCell and update all the existing tables with same link components

2022-10-05 09:15 UTC, workshur requested changes

2022-10-05 09:15 UTC, workshur commented on kafka-ui-react-app/src/components/Dashboard/ClustersWidget/ClustersWidget.tsx
> +            color="blue"
```suggestion
           
```

2022-10-06 09:58 UTC, Haarolean commented
@armenuikafka please take a look at the new dashboard, everything should look (almost) the same without any functionality issues.

2022-10-06 11:45 UTC, armenuikafka requested changes
Please make the "Topics" link design visible for user.
https://user-images.githubusercontent.com/104780608/194303908-1f2450d2-9a81-4999-aec9-b34503d86131.mov

2022-10-06 15:10 UTC, Haarolean commented
@armenuikafka @David-DB88 let's just get rid of this link at all

2022-10-06 15:16 UTC, armenuikafka commented
> @armenuikafka @David-DB88 let's just get rid of this link at all

@Haarolean do not redirect to Topics?

2022-10-06 15:36 UTC, armenuikafka commented
> Custom deployment will be available at http://pr2694.internal.kafka-ui.provectus.io

@David-DB88 , Topics count link still exists.

2022-10-06 16:06 UTC, David-DB88 commented
but I don't see the link anywhere @armenuikafka 
<img width="1464" alt="Screen Shot 2022-10-06 at 19 58 53" src="https://user-images.githubusercontent.com/58771979/194363212-826e125d-73fd-4073-b74d-b635668631b4.png">

2022-10-07 06:10 UTC, armenuikafka commented
@David-DB88 I'm checking http://pr2694.internal.kafka-ui.provectus.io/.    

https://user-images.githubusercontent.com/104780608/194479582-507e5128-403b-41c6-b184-2833c33c59a6.mov

2022-10-07 07:36 UTC, workshur approved these changes

2022-10-07 08:46 UTC, Haarolean commented
@armenuikafka a redeploy did help it seems, PTAL

2022-10-07 09:01 UTC, armenuikafka approved these changes

2022-10-10 15:36 UTC, merged