Migrate Topic Overview to the new version of table #2684
provectus/kafka-ui pull request #2704
Opened 2022-10-05 21:18 UTC by David-DB88

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Migrate Topic Overview to the new version of table

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-10-06 09:24 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Overview/ActionsCell.tsx
> +      {!data?.internal && !isReadOnly && data?.cleanUpPolicy === 'DELETE' ? (
Let's make dropdown item disabled instead of removing it from dom

2022-10-07 07:35 UTC, workshur requested changes

2022-10-07 07:35 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
> +    it('should check if the dropdown is not disabled when it is internal', () => {
it is disabled for internal

2022-10-07 07:35 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
> +    it('should check if the dropdown is not disabled when cleanUpPolicy is not DELETE', () => {
should be disabled

2022-10-07 07:35 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
> +      expect(screen.queryByText('Clear Messages')).toBeEnabled();
```suggestion
      expect(screen.getByLabelText('Dropdown Toggle')).toBeDisabled();
```

2022-10-07 07:35 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
> +      expect(screen.queryByText('Clear Messages')).toBeEnabled();
```suggestion
      expect(screen.getByLabelText('Dropdown Toggle')).toBeDisabled();
```

2022-10-10 07:49 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
>            cleanUpPolicy: CleanUpPolicy.DELETE,
remove this line to make experiment clear

2022-10-10 07:49 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
>          cleanUpPolicy: CleanUpPolicy.DELETE,
remove this line to make experiment clear

2022-10-10 07:50 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Overview/__test__/Overview.spec.tsx
>      it('should check if the dropdown action to be in visible', () => {
we can completely remove this `it` case

2022-10-13 07:27 UTC, workshur approved these changes

2022-10-13 07:27 UTC, workshur commented
@Haarolean pls take a look 👀

2022-10-19 04:44 UTC, armenuikafka approved these changes

2022-10-19 17:27 UTC, merged