#2544 message fields preview
provectus/kafka-ui pull request #2756
Opened 2022-10-14 19:45 UTC by Kris-K-Dev

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ ] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-10-19 10:19 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
> +    let parsedJson: object = {};
```suggestion
    let parsedJson;
```

2022-10-19 10:21 UTC, workshur reviewed
@Haarolean pls take a look 👀

2022-10-19 10:21 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/Topic/Messages/Message.tsx
> +            {item.field}: {get(parsedJson, item.path)}
```suggestion
            {item.field}: {get(parsedJson || {}, item.path)}
```

2022-10-19 17:11 UTC, Haarolean commented
> @Haarolean pls take a look 👀

already on it :)

2022-10-19 17:17 UTC, Haarolean commented
Looks good, a few suggestions:
1. Let's make the created fields editable or display their paths at least
2. Let's display "x is required" right after user tries to press "ok". That's disturbing to see the red text instantly after you open up the modal window.

@kristi-dev

2022-10-20 19:16 UTC, kristi-dev commented
> Looks good, a few suggestions:
> 
> 1. Let's make the created fields editable or display their paths at least
> 2. Let's display "x is required" right after user tries to press "ok". That's disturbing to see the red text instantly after you open up the modal window.
> 
> @kristi-dev

Done both 
https://somup.com/c36Yqov3Vc

2022-10-21 21:35 UTC, Haarolean approved these changes
@workshur hey, are you done with the review?

2022-10-24 11:27 UTC, workshur approved these changes

2022-10-24 19:28 UTC, Haarolean commented
@armenuikafka I gave it a quick glance, works fine, please take a look, you might find something

2022-10-25 09:31 UTC, armenuikafka requested changes
could we keep the preview in case of cancelling the editing

https://user-images.githubusercontent.com/104780608/197735764-f3c55291-b512-4f30-b18c-8bc0e707188b.mov

2022-10-25 10:00 UTC, armenuikafka commented
@Haarolean maybe we need some limitation for fields or we can show not all content

<img width="1550" alt="limitation" src="https://user-images.githubusercontent.com/104780608/197742910-103da47c-b905-4c8b-9643-80a12f5b3531.png">

2022-10-25 20:07 UTC, Haarolean commented
> @Haarolean maybe we need some limitation for fields or we can show not all content
> 
> <img alt="limitation" width="1550" src="https://user-images.githubusercontent.com/104780608/197742910-103da47c-b905-4c8b-9643-80a12f5b3531.png">

@kristi-dev can we add some limit to show this? the rest can be hidden like this: "lorem impsum..."

2022-10-25 23:02 UTC, kristi-dev commented
> > @Haarolean maybe we need some limitation for fields or we can show not all content
> > <img alt="limitation" width="1550" src="https://user-images.githubusercontent.com/104780608/197742910-103da47c-b905-4c8b-9643-80a12f5b3531.png">
> 
> @kristi-dev can we add some limit to show this? the rest can be hidden like this: "lorem impsum..."

yes, fix this

2022-10-25 23:06 UTC, kristi-dev commented
> could we keep the preview in case of cancelling the editing
> 
>  preview.edit.mov

i changed edit functionality, so now we can see the list of fields above while editing and also, we are able to just close without editing and that field remains for preview

2022-11-07 07:02 UTC, armenuikafka approved these changes

2022-11-07 15:34 UTC, merged