Topic creation: lock page until creation request finished
provectus/kafka-ui pull request #2815
Opened 2022-10-24 15:36 UTC by habrahamyanpro

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ ] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-10-26 07:38 UTC, workshur requested changes
Please check the documentation of ReactQuery library. `createTopic` mutation already provide info about fetching status

2022-10-28 07:40 UTC, workshur commented on kafka-ui-react-app/src/components/Topics/New/New.tsx
> +
can we use id submitting property of TopicForm component?

2022-11-10 10:45 UTC, workshur approved these changes

2022-11-10 10:45 UTC, workshur commented
@Haarolean, this one is ready for QA

2022-11-10 10:53 UTC, Mgrdich reviewed
please check the linter error.
`'connectors' is defined but never used`

2022-11-21 09:22 UTC, armenuikafka approved these changes
..

2022-11-25 03:21 UTC, Haarolean commented
@habrahamyanpro can we fix the conflicts and merge?

2022-11-25 14:23 UTC, merged