Don't Dismiss Produce Message pane after Send
provectus/kafka-ui pull request #2854
Opened 2022-11-01 06:24 UTC by winnie-chiu

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
In the produce message pane add a new checkbox "Keep the contents", unchecked by default. 
If the checkbox is being checked, leave the key/value content and pane as it is.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2022-11-01 13:51 UTC, kristi-dev approved these changes

2022-11-09 07:18 UTC, armenuikafka requested changes
"Keep the contents" is unchecked, but data for key and value are kept with producing new message


https://user-images.githubusercontent.com/104780608/200763938-9afee887-5fdc-4b60-bf75-317e97e5485d.mov

2023-02-03 09:30 UTC, Haarolean commented
@winnie-chiu can you fix the issue mentioned in [the comment](https://github.com/provectus/kafka-ui/pull/2854#pullrequestreview-1173446892)?

2023-02-07 06:20 UTC, winnie-chiu commented
@Haarolean I feel this task is out of my league. I'm not able to fix the issue mentioned above.

2023-02-08 10:33 UTC, Haarolean commented
@winnie-chiu ok no worries, we'll do that :) thank you

2023-03-02 08:40 UTC, David-DB88 commented on kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
> +      onSubmit();
ok

2023-03-02 08:52 UTC, David-DB88 commented on kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
> +      onSubmit();
@Mgrdich this function is not mine, as I understand it, it only closes the sidebar, I will rename it

2023-03-02 08:56 UTC, David-DB88 commented on kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
> +                <div>
we do not need div

2023-03-02 09:08 UTC, Mgrdich approved these changes

2023-03-02 09:08 UTC, Mgrdich commented on kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
> +                <div>
then we can delete it.

2023-03-02 09:08 UTC, Mgrdich commented on kafka-ui-react-app/src/components/Topics/Topic/SendMessage/SendMessage.tsx
> +      onSubmit();
yeah i want to understand when we should trigger that close thing , cause from only reading of it , the request the BE is happening  -> so logically `onSubmit` should work, `if (!keepContents) {` `setValues` is what is happening to the ui state of the component.

if it is not onSubmit handler then it should be renamed

2023-03-02 09:11 UTC, David-DB88 commented
almost done it, remove div and renamed function to closeSidebar()

2023-03-15 14:21 UTC, Haarolean requested changes
<img width="476" alt="image" src="https://user-images.githubusercontent.com/1494347/225338024-13bae291-307a-4a51-ba04-dc737713830c.png">
visually looks ugly, pending design solution

2023-03-20 15:48 UTC, Haarolean commented
Please use this design solution
https://www.figma.com/file/ZkvysdRUmt9p2PDNU3a9WU/Kafka-UI?node-id=3298-11325

2023-03-20 16:00 UTC, David-DB88 commented
ok

2023-04-26 04:18 UTC, Haarolean approved these changes

2023-04-26 04:19 UTC, merged