fix(3143): passes prometheus basic auth credentials
provectus/kafka-ui pull request #3201
Opened 2023-01-06 14:23 UTC by wanisfahmyDE

Co-authored-by: theurichde <tim.heurich@idealo.de>

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
We extended the PrometheusMetricsRetriever to account for Prometheus basic auth credentials conditionally if passed.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

![](https://i.ytimg.com/vi/hNjjaEoa0Xw/maxresdefault.jpg)

2023-01-06 16:15 UTC, Haarolean requested changes

2023-01-06 16:15 UTC, Haarolean commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/PrometheusMetricsRetriever.java
> +    Integer port = Optional.ofNullable(metricsConfig.getPort()).orElse(DEFAULT_EXPORTER_PORT);
this should be a primitive since it can't be null

2023-01-06 16:15 UTC, Haarolean commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/metrics/PrometheusMetricsRetriever.java
> +    if (null != metricsConfig.getUsername() && null != metricsConfig.getPassword()) {
Let's flip these conditions, like `x != null && y != null`, that's core java-ish codestyle :)

2023-01-06 17:07 UTC, wanisfahmyDE commented
Hey @Haarolean, all done. can you have another look? :)

2023-01-12 07:35 UTC, Haarolean approved these changes

2023-01-12 07:42 UTC, iliax approved these changes

2023-01-16 13:53 UTC, merged

2023-01-16 13:53 UTC, Haarolean commented
@theurichde @wanisfahmyDE thank you for the contribution!