"Copy to clipboard" doesn't work #2819
provectus/kafka-ui pull request #3394
Opened 2023-02-23 10:40 UTC by David-DB88

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
set a warning message on copyToClipboard if user use http

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2023-02-23 11:01 UTC, Haarolean approved these changes

2023-02-23 11:01 UTC, Haarolean commented on kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
> +          'Copying to clipboard is unavailable due to unsecured (non-HTTPS) connection!',
```suggestion
          'Copying to clipboard is unavailable due to unsecured (non-HTTPS) connection',
```

2023-02-23 11:05 UTC, workshur commented on kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
> +      showAlert('custom', {
I would suggest to use `warning` here

2023-02-23 11:52 UTC, David-DB88 commented on kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
> +          'Copying to clipboard is unavailable due to unsecured (non-HTTPS) connection!',
ok

2023-02-23 11:52 UTC, David-DB88 commented on kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
> +      showAlert('custom', {
ok

2023-02-23 12:16 UTC, Haarolean approved these changes

2023-02-24 08:10 UTC, workshur commented on kafka-ui-react-app/src/lib/hooks/useDataSaver.ts
> +        title: '',
```suggestion
        title: 'Warning',
```

2023-02-24 08:10 UTC, workshur approved these changes
Please add title for the message

2023-02-24 12:50 UTC, David-DB88 commented
ок

2023-02-24 19:50 UTC, Mgrdich approved these changes

2023-02-27 11:52 UTC, armenuikafka requested changes
Not able to copy the message because of connection.

https://user-images.githubusercontent.com/104780608/221556354-2cec4ad8-574d-4f34-acc8-dcd446de00fa.mov

2023-02-28 13:56 UTC, David-DB88 commented
@armenuikafka yes i showing warning  message because the connection is non Https and not secure  and the copy functionality is disabled for http, so it's working fine

2023-03-01 07:37 UTC, workshur approved these changes

2023-03-06 09:46 UTC, Haarolean approved these changes

2023-03-07 06:36 UTC, merged