refactor CG List & details page
provectus/kafka-ui pull request #3508
Opened 2023-03-16 07:49 UTC by workshur

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ ] My changes generate no new warnings (e.g. Sonar is happy)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2023-03-17 09:46 UTC, Mgrdich approved these changes

2023-03-17 09:46 UTC, Mgrdich commented on kafka-ui-react-app/src/components/ConsumerGroups/Details/Details.tsx
> +  const routeParams = useAppParams<ClusterGroupParam>();
in my opinion de-structuring it here is better, cause maybe in the future someone might try to use `routeParams`, and get into reference and memoization problems.

2023-03-20 13:30 UTC, Haarolean commented
https://user-images.githubusercontent.com/1494347/226354758-bc8b7936-eda5-4115-aab8-818ec9a13b17.mov
some fonts flickering

2023-03-20 13:31 UTC, Haarolean requested changes
https://github.com/provectus/kafka-ui/pull/3508#issuecomment-1476238383

2023-03-21 13:50 UTC, workshur commented
> 

I'm disabling table during fetch. The response time is high and the list might be changed

2023-03-21 15:10 UTC, Haarolean approved these changes

2023-03-23 15:40 UTC, merged