Fix #3417
provectus/kafka-ui pull request #3580
Opened 2023-03-29 01:56 UTC by blacktower88

Remove success message in case of adding the Topic

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Remove success message in case of adding the Topic
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2023-03-29 02:14 UTC, Haarolean requested changes
HI, thanks for the contribution. Please take a look at the comments.

2023-03-29 02:14 UTC, Haarolean commented on kafka-ui-react-app/src/lib/hooks/api/topics.ts
> -        client.invalidateQueries(topicKeys.all(clusterName));
`client.invalidateQueries(topicKeys.all(clusterName));`
this has to be left intact I suppose
Also, please remove the code instead of commenting it

2023-03-29 02:15 UTC, Haarolean commented
Also, the build

2023-03-29 02:42 UTC, blacktower88 commented
Sorry, I still have something confused.  Do I need to build the whole project ? As I only fix some part of the frontend.

2023-03-30 05:54 UTC, Haarolean commented
> Sorry, I still have something confused. Do I need to build the whole project ? As I only fix some part of the frontend.

I mean the merge checks, frontend build is failing
<img width="872" alt="image" src="https://user-images.githubusercontent.com/1494347/228742264-1b180c26-da99-4863-a076-17c1d302dd7c.png">

2023-03-31 09:25 UTC, David-DB88 approved these changes

2023-03-31 11:47 UTC, Mgrdich approved these changes

2023-04-02 01:01 UTC, blacktower88 commented
Hi, I'm very sorry that I accidentally clicked the remove assignment icon, can you please assign to me again? I wanted to check something, but I hit the wrong button. It was a silly mistake and I apologize for any inconvenience.

2023-04-03 04:40 UTC, Haarolean commented
> Hi, I'm very sorry that I accidentally clicked the remove assignment icon, can you please assign to me again? I wanted to check something, but I hit the wrong button. It was a silly mistake and I apologize for any inconvenience.

lol no worries

2023-04-03 04:41 UTC, Haarolean commented
@blacktower88 ping me once you're done, we'll fix e2e tests

2023-04-11 07:47 UTC, blacktower88 commented
@Haarolean I am not sure but I think I finished. Frontend build and test was passed. Please let me know if there is anything to be corrected.

2023-04-20 17:19 UTC, Haarolean approved these changes

2023-04-24 12:15 UTC, merged