#356 added endpoint to fetch all cluster connectors
provectus/kafka-ui pull request #361
Opened 2021-04-07 13:23 UTC by RamazanYapparov

Fixes #356

2021-04-07 16:29 UTC, workshur approved these changes
LGTM

2021-04-08 17:39 UTC, germanosin requested changes

2021-04-09 09:21 UTC, RamazanYapparov commented on kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
> +            - RUNNING
Fixed, thanks

2021-04-09 09:21 UTC, RamazanYapparov commented on kafka-ui-contract/src/main/resources/swagger/kafka-ui-api.yaml
> +            - source
Fixed, thanks

2021-04-09 09:22 UTC, RamazanYapparov commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
> +    return getConnects(clusterName)
Fixed, thanks

2021-04-09 09:22 UTC, RamazanYapparov commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
> +            .hasFailedTasks(triple.getRight().stream()
Fixed, thanks

2021-04-09 09:22 UTC, RamazanYapparov commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/KafkaConnectService.java
> +        .map(triple -> new FullConnectorInfo()
Fixed, thanks

2021-04-15 08:15 UTC, merged