changed redirect logic location from Dashboard.tsx to PageContainer.t…
provectus/kafka-ui pull request #3655
Opened 2023-04-11 10:18 UTC by David-DB88

…sx and test cases

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
changed redirect logic location from Dashboard.tsx to PageContainer.tsx and test cases
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2023-04-14 11:03 UTC, David-DB88 commented on kafka-ui-react-app/src/components/PageContainer/__tests__/PageContainer.spec.tsx
> +  describe('Redirect to the Wizard page', () => {
mockedNavigate called 3 times with different data render component so we cant use beforeEach because it different every time

2023-05-05 14:55 UTC, Mgrdich reviewed
Maybe we should write just minor tests for the dashboard page , to check if some component exits or not , we can even mock the big components if there are any.

2023-05-10 05:24 UTC, Haarolean commented
The issue hasn't been fixed, I don't see how adding yet another redirect is gonna fix the issue

2023-05-30 07:42 UTC, workshur approved these changes
Code looks ok

2023-06-02 13:28 UTC, Haarolean requested changes
Implementation is invalid, no RBAC is taken into consideration

2023-06-02 13:30 UTC, Haarolean approved these changes

2023-06-15 18:16 UTC, Mgrdich approved these changes

2023-06-16 04:38 UTC, merged