Opt version check with versionTag #2753
provectus/kafka-ui pull request #3827
Opened 2023-05-16 10:51 UTC by David-DB88

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
checking if version equals versionTag and show it
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2023-05-17 09:57 UTC, Haarolean requested changes

2023-05-17 11:31 UTC, David-DB88 commented on kafka-ui-react-app/src/components/Version/Version.tsx
> +  const currentVersion = version?.match(versionTag)
ок

2023-05-20 08:57 UTC, Mgrdich approved these changes

2023-05-22 10:10 UTC, Haarolean approved these changes

2023-05-22 10:10 UTC, merged