RBAC: Implement roles by github teams
provectus/kafka-ui pull request #4093
Opened 2023-08-04 13:59 UTC by Haarolean

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

2023-08-04 14:10 UTC, iliax requested changes

2023-08-04 14:10 UTC, iliax commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java
> +                .filter(s -> s.getType().equals("organization"))
ORGANIZATION constant?

2023-08-04 14:10 UTC, iliax commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java
>    private static final String ORGANIZATION_NAME = "login";
?

2023-08-04 14:10 UTC, iliax commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java
> +    var mappedTeams = rawTeams
please write type here for better readability

2023-08-04 14:10 UTC, iliax commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java
> +                    .distinct()
distinct not useful here

2023-08-04 14:14 UTC, iliax requested changes

2023-08-07 14:01 UTC, Haarolean commented on kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/rbac/extractor/GithubAuthorityExtractor.java
>    private static final String ORGANIZATION_NAME = "login";
Yes it is!

2023-08-07 15:01 UTC, merged