Issue#207 Requests to KsqlDb from UI
provectus/kafka-ui pull request #786
Opened 2021-08-11 13:52 UTC by abelgibayev

**What changes did you make?** (Give an overview)
- Added KsqlDb page
- Added ability to make ksql queries
**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "X" next to an item)

- [ ] No need to
- [ ] Manually(please, describe, when necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings(e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

2021-08-11 14:53 UTC, workshur reviewed
Great job @abelgibayev! 

Please add some screenshots and check SonarCloud message. It would be great if we can avoid adding code smells and Increase coverage up to 80%

2021-08-11 14:53 UTC, workshur commented on kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
> +  const [isModalShown, setIsShow] = useState(false);
```suggestion
  const [isModalShown, setIsModalShown] = useState(false);
```

Minor. just a standard naming convention

2021-08-11 14:53 UTC, workshur commented on kafka-ui-react-app/src/components/KsqlDb/List/List.tsx
> +                ))}
Add a placeholder for case when there are no rows.

2021-08-11 14:53 UTC, workshur commented on kafka-ui-react-app/src/components/common/SQLEditor/SQLEditor.tsx
> +SQLEditor.displayName = 'JSONEditor';
```suggestion
SQLEditor.displayName = 'SQLEditor';
```

2021-08-11 14:53 UTC, workshur commented on kafka-ui-react-app/src/components/common/SQLEditor/__tests__/SQLEditor.spec.tsx
> +describe('JSONEditor component', () => {
```suggestion
describe('SQLEditor component', () => {
```

2021-08-11 18:03 UTC, burusha16 requested changes
Can we discuss ui/ux with @workshur and @germanosin? I think we have wrong ui/ux for this feature.

2021-08-11 18:03 UTC, burusha16 commented on kafka-ui-react-app/src/components/KsqlDb/QueryModal/QueryModal.tsx
> +      ksql: '',
there is second non required param `additionalProperties`.  Don't forget to add it.

2021-08-17 10:47 UTC, workshur approved these changes

2021-08-17 12:06 UTC, burusha16 approved these changes

2021-08-17 12:06 UTC, burusha16 commented on kafka-ui-react-app/src/components/common/Tabs/Tabs.tsx
> +Tabs.displayName = 'Tabs';
nit: same with display name

2021-08-17 12:06 UTC, burusha16 commented
🔥🔥🔥

2021-08-18 10:24 UTC, merged