ISSUE-849: Use a map between topics and message-names when using ProtobufFile
provectus/kafka-ui pull request #854
Opened 2021-09-06 13:20 UTC by zarezadeh

- [x] **Breaking change?** This is a breaking change. The field `protobufMessageName` used in the configuration file was of type string but after this change, it will be of type Map. The following configuration snippet:
```
protobufFile: some-proto-definition.proto
protobufMessageName: SomeMessageName
```
should be converted to:
```
protobufFile: some-proto-definition.proto
protobufMessageName:
  _default: SomeMessageName
```

**What changes did you make?** Added the ability to specify separate message types for each topic when using ProtobufFile for deserialization. The configuration `protobufMessageName` is now a map between the topic name and the message name. The key `_default` is used for specifying the message name for all other topics not defined explicitly.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "X" next to an item)

- [ ] No need to
- [x] Manually(please, describe, when necessary)
- [x] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings(e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

2021-09-07 10:37 UTC, iliax commented
@zarezadeh thank you for PR!
Here some improvements to consider:
1. Lets keep configs backward-compatible: use `protobufMessageName` property value as default message and `protobufTopicMessageName` map for explicit topic mapping 
2. please add mapping check in ProtobufFileRecordSerDe::serialize method: https://github.com/provectus/kafka-ui/blob/c19b9a6867d3bb2b3e8602c96148062f6133cb7e/kafka-ui-api/src/main/java/com/provectus/kafka/ui/serde/ProtobufFileRecordSerDe.java#L81 
3. In tests please add manual messages creations rather than Base64. Here is a sample how you can do it:
```    
DynamicMessage.Builder builder = protobufSchema.newMessageBuilder("messageNameHere");
JsonFormat.parser().merge("{ \"name\": \"My Name\", \"email\": \"test@test.com\" }", builder);
byte[] bytes =  builder.build().toByteArray();
```

2021-09-07 10:40 UTC, iliax requested changes
see https://github.com/provectus/kafka-ui/pull/854#issuecomment-914193841

2021-09-07 13:11 UTC, zarezadeh commented
@iliax thanks for your review, I applied your suggestions in the code.
But I think there's still one case that we should take into account: What if the provided messageName for a given topic does not exist in the protobuf definition? Should we handle it or is it the user's responsibility to provide proper configuration?

2021-09-07 15:03 UTC, iliax commented
> @iliax thanks for your review, I applied your suggestions in the code.
> But I think there's still one case that we should take into account: What if the provided messageName for a given topic does not exist in the protobuf definition? Should we handle it or is it the user's responsibility to provide proper configuration?

Yes, it is a good point. I think we definitely should not fall with NPE when provided name not found. We should either check names in constructor ( toDescriptor(..) != null) or in serialize/derialize. (requireNonNull(..))

2021-09-08 08:44 UTC, iliax requested changes
see comment above

2021-09-13 05:54 UTC, germanosin approved these changes
LGTM

2021-09-13 06:19 UTC, iliax approved these changes

2021-09-13 06:20 UTC, merged

2021-09-13 06:21 UTC, iliax commented
@zarezadeh thank you for PR!